object ExceptionSyll {
//  def divider(x:Float,y:Float): Float ={
//    if (y==0)
//      throw  new Exception("除数不能为0")
//    else
//      x/y
//  }

  def main(args: Array[String]): Unit = {
//    try
//      {
//        print(divider(10, 0));
//      }catch{
//      case  ex:Exception=>println("1"+ex)
//    }
//    finally {
//      print("11112222")
//    }
    print(2)
  }
}
